### ISSUE TITLE
Incluir estrutura de topicos no capitulo 1

### ISSUE THREAD

**Issue by ana-dev1** [cesarvasconcelos/repo-gitflow#1]
Ola, Cesar.
Talvez fosse interessante incluir uma estrutura de topicos, como objetivos, metodologia, justificativa, etc. no capitulo de introducao.

**Comment by cesarvasconcelos** [comment]
Verdade, Ana. Vou abrir uma feature branch propria para esta estrutura. Obrigado por colaborar.

**Comment by cesarvasconcelos** [comment]
Esta colaboração de Ana foi incluida no projeto via [9c7f85d5](https://github.com/cesarvasconcelos/repo-gitflow/commit/9c7f85d58cf05eb3cfa9acb3488337dbcc6135ff)
